### ISSUE TITLE
games.py

### ISSUE THREAD

**Issue by geoffrey974** [zeemil/ecoleit-1sql-esport#5]
from .Model import Model

class Game(Model):
	def show(self):
		query = "SELECT * from games"
		cursor = self.connection.cursor()
		cursor.execute(query)
		records = cursor.fetchall()
		print("Nbr rows: ", cursor.rowcount, "\n")
		for row in records:
			print("Id = ", row[0] )
			print("title = ", row[1])
			print("type  = ", row[2])
			
	def create(self):
		print("games information:")
		title = input("title: ")
		type = input("type: ")
		
		query = "INSERT INTO games (title, types) values (%s, %s)"
		
		tuple = (title, type)
		
		cursor = self.connection.cursor()
		cursor.execute(query, tuple)
		self.connection.commit()
		
		print("Insert successful: ")
		self.read( cursor.lastrowid )
		
		
	def read(self, id = None):
		if id is None:
			id = input("Select id: ")
			
		query = "SELECT * from games where id=%s"	
		cursor = self.connection.cursor(dictionary=True)
		cursor.execute( query,(id,) )
		record = cursor.fetchone()
		
		if record:
			for key, value in record.items():
				print(key,":", value)
		else:
			print("no record found for id " + id)
		
	def update(self):
		id = input("select id: ")
		
		query = "SELECT * from games where id=%s"	
		cursor = self.connection.cursor(dictionary=True)
		cursor.execute( query,(id,) )
		record = cursor.fetchone()
		
		if record:
			print("UPDATE this games")
			self.read(id)
			
			field_to_update = input("Select a field to update:")
			value = input("Set a new value: ")
			
			query = "UPDATE games SET "+field_to_update+" = %s WHERE id = %s" 
			cursor = self.connection.cursor(dictionary=True)
			tuple = (value, id)
			cursor.execute( query, tuple )
			self.connection.commit()
			
			print("")
			print("Record saved")
			self.read(id)
		
	def delete(self):
		id = input("select id: ")
		
		query = "DELETE FROM games WHERE id = %s"
		cursor = self.connection.cursor(dictionary=True)
		tuple = (id,)
		cursor.execute( query, tuple )
		self.connection.commit()
		
		print("Record deleted")

**Comment by zeemil** [comment]
Merci :-)
